# Generated by Django 4.1 on 2023-02-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticinformation',
            old_name='youtube',
            new_name='linked_in',
        ),
        migrations.RenameField(
            model_name='staticinformation',
            old_name='telegram',
            new_name='twitter',
        ),
    ]
