# Generated by Django 4.1 on 2023-05-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0004_services_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
