# Generated by Django 4.1 on 2023-01-27 18:04

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='Name')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='car_marks')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Год выпуска')),
                ('country', models.JSONField(blank=True, null=True, verbose_name='Страна производства')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='cars')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carmarks')),
            ],
        ),
    ]
