# Generated by Django 4.1 on 2023-01-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна производства'),
        ),
    ]
