# Generated by Django 4.1 on 2023-02-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_cars_carsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='State name')),
                ('code', models.JSONField(blank=True, null=True, verbose_name='State code')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True, verbose_name='Name')),
                ('zip', models.CharField(max_length=255, verbose_name='City zip')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.states')),
            ],
        ),
    ]
