# Generated by Django 4.1 on 2023-02-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_states_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmarks',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carsmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carsmodel',
            name='model',
        ),
    ]
