# Generated by Django 4.1 on 2023-02-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_carmarks_image_remove_carsmodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsmodel',
            name='country',
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('SUV', 'SUV'), ('Pickup', 'Pickup')], default='Car', max_length=255, verbose_name='Vehicle type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.carmarks'),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='name',
            field=models.JSONField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='carsmodel',
            name='year',
            field=models.CharField(default='2019', max_length=4, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
