# Generated by Django 4.1 on 2023-02-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_states_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(verbose_name='Distance')),
                ('date', models.DateField()),
                ('vehicle_runs', models.CharField(choices=[('Yes', '1'), ('No', '0')], max_length=255, verbose_name='Vehicle Runs')),
                ('ship_via_id', models.CharField(choices=[('Open', '1'), ('Enclosed', '2')], max_length=255, verbose_name='Ship via id')),
                ('ship_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_from_order', to='main.city')),
                ('ship_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_to_orders', to='main.city')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carsmodel')),
            ],
        ),
    ]
