# Generated by Django 4.1 on 2023-02-04 13:46

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='email',
            field=models.EmailField(default='dadamuhames@gmail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leads',
            name='nbm',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[main.models.is_numeric_validator], verbose_name='Nbm'),
        ),
        migrations.AddField(
            model_name='leads',
            name='price',
            field=models.FloatField(default=2000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price'),
            preserve_default=False,
        ),
    ]
