# Generated by Django 4.1 on 2023-02-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_city_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsmodel',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('SUV', 'SUV'), ('Pickup', 'Pickup')], default='Car', max_length=255, verbose_name='Vehicle type'),
        ),
    ]
