# Generated by Django 4.1 on 2023-02-05 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_carsmodel_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
