# Generated by Django 4.1 on 2023-02-05 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_leads_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
