# Generated by Django 4.1 on 2023-02-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_carsmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Distance'),
        ),
    ]
