# Generated by Django 4.1 on 2023-02-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_leads_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='ship_via_id',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=255, verbose_name='Ship via id'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='vehicle_runs',
            field=models.CharField(choices=[('1', '1'), ('0', '0')], max_length=255, verbose_name='Vehicle Runs'),
        ),
    ]
