# Generated by Django 4.1 on 2023-02-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_leads_ship_via_id_alter_leads_vehicle_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='zip',
            field=models.CharField(max_length=5, unique=True, verbose_name='City zip'),
        ),
        migrations.AlterUniqueTogether(
            name='leads',
            unique_together={('ship_from', 'ship_to')},
        ),
    ]
