# Generated by Django 4.1 on 2023-02-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_city_zip_alter_leads_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leads',
            unique_together=set(),
        ),
    ]
