# Generated by Django 4.1 on 2023-02-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_leads_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='vehicle_runs',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=255, verbose_name='Vehicle Runs'),
        ),
    ]
