# Generated by Django 4.1 on 2023-02-07 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_leads_vehicle_runs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='price',
            new_name='price_first_tarif',
        ),
        migrations.AddField(
            model_name='leads',
            name='price_second_tarif',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price'),
        ),
    ]
