# Generated by Django 4.1 on 2023-02-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_applications_aplicationnbm'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered')], default='Accepted', max_length=255, verbose_name='Status'),
        ),
    ]
