# Generated by Django 4.1 on 2023-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_applications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='car_year',
            field=models.CharField(default=2004, max_length=4, verbose_name='Car year'),
            preserve_default=False,
        ),
    ]
