# Generated by Django 4.1 on 2023-02-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_leads_car_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='car_year',
        ),
        migrations.AlterField(
            model_name='applications',
            name='tarif',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=255, verbose_name='Tarif'),
        ),
    ]
