# Generated by Django 4.1 on 2023-02-08 10:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_leads_car_year_alter_applications_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='car_year',
            field=models.CharField(default=2007, max_length=4, validators=[main.models.is_numeric_validator], verbose_name='Car year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leads',
            name='car_year',
            field=models.CharField(default=2007, max_length=4, validators=[main.models.is_numeric_validator], verbose_name='Car year'),
            preserve_default=False,
        ),
    ]
