# Generated by Django 4.1 on 2023-02-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_applications_car_year_leads_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='adres',
            field=models.CharField(default='soem dadadsd', max_length=255, verbose_name='Adres'),
            preserve_default=False,
        ),
    ]
