# Generated by Django 4.1 on 2023-02-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_applications_deckription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='ship_via_id',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Enclosed')], max_length=255, verbose_name='Ship via id'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='tarif',
            field=models.CharField(choices=[('1', '500$ tarif'), ('2', '200$ tarif')], max_length=255, verbose_name='Tarif'),
        ),
    ]
