# Generated by Django 4.1 on 2023-02-09 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_applications_ship_via_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='final_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Final Price'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Canseled', 'Canseled')], default='Accepted', max_length=255, verbose_name='Status'),
        ),
    ]
