# Generated by Django 4.1 on 2023-02-09 18:22

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_applications_final_price_alter_applications_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbm', models.CharField(blank=True, max_length=10, null=True, validators=[main.models.is_numeric_validator], verbose_name='Nbm')),
                ('status', models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Рассмотрено', 'Рассмотрено'), ('Отклонено', 'Отклонено')], default='На рассмотрении', max_length=255, verbose_name='Status')),
            ],
        ),
    ]
