# Generated by Django 4.1 on 2023-02-10 12:39

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_leads_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortapplication',
            name='nbm',
            field=models.CharField(default='111111', max_length=10, validators=[main.models.is_numeric_validator], verbose_name='Nbm'),
            preserve_default=False,
        ),
    ]
