# Generated by Django 4.1 on 2023-02-11 08:53

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_shortapplication_nbm'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='contact_else',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[main.models.is_numeric_validator], verbose_name='Contact else'),
        ),
        migrations.AddField(
            model_name='applications',
            name='contact_me',
            field=models.BooleanField(default=True, verbose_name='Contact me'),
        ),
    ]
