# Generated by Django 4.1 on 2023-02-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_applications_contact_else_applications_contact_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
