# Generated by Django 4.1 on 2023-02-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_applications_car_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='adres_type',
            field=models.CharField(choices=[('Residentional adress', 'Residentional adress'), ('Business adress', 'Business adress')], default='Residentional adress', max_length=255, verbose_name='Adres type'),
            preserve_default=False,
        ),
    ]
