# Generated by Django 4.1 on 2023-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_applications_adres_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='nbm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nbm'),
        ),
    ]
