# Generated by Django 4.1 on 2023-03-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_leads_nbm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmigaSkiAplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('nmb', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, choices=[('0', 'I want a free quote'), ('1', 'I have an existing order'), ('2', 'I want to book a shipment'), ('3', 'Other questions')], max_length=255, null=True, verbose_name='Subject')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
