# Generated by Django 4.1 on 2023-03-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_amigaskiaplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmigaSkiAplication',
            new_name='SomeAplication',
        ),
    ]
