# Generated by Django 4.1 on 2023-05-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_rename_amigaskiaplication_someaplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="applications",
            name="business_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Business name"
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="exact_business_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Exact business name",
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="exact_someone_fullname",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Exact someone fullname",
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="exact_someone_phone",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Exact someone phone",
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="someone_fullname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Someone fullname"
            ),
        ),
        migrations.AddField(
            model_name="applications",
            name="someone_phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Someone phone"
            ),
        ),
    ]
