# Generated by Django 4.1 on 2024-03-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_leads2'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads2',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
